# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.15

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^cache/
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.1
  hooks:
  - id: ruff-check
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.3.0
  hooks:
  - id: mypy
    exclude: pep600_compliance/tools/calculate_symbol_versions.py
    additional_dependencies:
      - types-requests

- repo: https://github.com/henryiii/flake8-lazy
  rev: 5fed9a818f2583f0403aed779bf2b6c9aa8d25f4  # frozen: v0.8.5
  hooks:
  - id: flake8-lazy
    args: ["--apply=native"]
    files: '^pep600_compliance'
    exclude: "^pep600_compliance/tools/"
